[package]
name = "oombak_rs"
version.workspace = true
edition = "2021"
authors.workspace = true
license-file.workspace = true
repository.workspace = true

[dependencies]
bitvec = "1.0.1"
libloading = "0.8.5"
thiserror = "2.0.6"

[build-dependencies]
cmake = "0.1.54"
rerun_except = "1.0.0"
